import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navbar";
import Link from "next/link";
import {
  Facebook,
  Instagram,
  Linkedin,
  MoveUpRight,
  Mail,
  Phone,
  MessageCircle,
} from "lucide-react";

export const metadata: Metadata = {
  title: "NurCode",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={""}>
        <header className="fixed z-10 top-10 w-full left-0 flex justify-center px-5 md:px-auto">
          <NavBar />
        </header>

        <main className="w-full ">{children}</main>

        <footer className="px-5 md:px-20 w-full pb-16 *:text-center">
          <article className="rounded-2xl bg-gradient-to-r from-blue-400  via-blue-600 to-blue-900  md:min-h-14 *:text-white px-5 md:px-32 py-10">
            <section className="flex flex-col md:flex-row md:justify-between items-center justify-center gap-3">
              <div className="flex flex-col gap-1 md:items-start items-center">
                <Link href={"/"} className="font-bold text-xl md:text-3xl">
                  NUR<span className="text-blue-900">CODE</span>
                </Link>
                <span className="text-sm font-medium text-neutral-100">
                  &copy; 2026 NurCode. Todos os direitos reservados.
                </span>
              </div>

              <ul className="flex gap-3 items-center">
                <li>
                  <Link
                    href="https://www.facebook.com"
                    target="_blank"
                    rel="noopener noreferrer"
                    aria-label="Facebook"
                    className="inline-flex items-center justify-center w-9 h-9 rounded-full bg-white/10 text-white hover:bg-white/20 transition-transform hover:scale-105"
                    title="Facebook"
                  >
                    <Facebook className="w-4 h-4" />
                  </Link>
                </li>

                <li>
                  <Link
                    href="https://www.instagram.com"
                    target="_blank"
                    rel="noopener noreferrer"
                    aria-label="Instagram"
                    className="inline-flex items-center justify-center w-9 h-9 rounded-full bg-white/10 text-white hover:bg-white/20 transition-transform hover:scale-105"
                    title="Instagram"
                  >
                    <Instagram className="w-4 h-4" />
                  </Link>
                </li>

                <li>
                  <Link
                    href="https://wa.me/"
                    target="_blank"
                    rel="noopener noreferrer"
                    aria-label="WhatsApp"
                    className="inline-flex items-center justify-center w-9 h-9 rounded-full bg-white/10 text-white hover:bg-white/20 transition-transform hover:scale-105"
                    title="WhatsApp"
                  >
                    <MessageCircle className="w-4 h-4" />
                  </Link>
                </li>

                <li>
                  <Link
                    href="https://www.linkedin.com"
                    target="_blank"
                    rel="noopener noreferrer"
                    aria-label="LinkedIn"
                    className="inline-flex items-center justify-center w-9 h-9 rounded-full bg-white/10 text-white hover:bg-white/20 transition-transform hover:scale-105"
                    title="LinkedIn"
                  >
                    <Linkedin className="w-4 h-4" />
                  </Link>
                </li>
              </ul>
            </section>

            <hr className="w-full rounded-2xl bg-white my-8" />

            <section
              id="message-and-address-contact"
              className="flex flex-col md:flex-row md:justify-between items-center gap-6 md:items-start justify-center"
            >
              <div className="w-80  md:text-xl font-semibold italic">
                <p>
                  "As dificuldades não existem para nos parar, mas para revelar
                  do que somos capazes."
                </p>
              </div>

              <div className="grid grid-cols-1 gap-6 md:gap-2 md:rid-cols-2">
                <article className="grid grid-cols-1 justify-start">
                  <h3 className="font-semibold text-xl mb-2">Fale Conosco</h3>
                  <ul className="grid grid-cols-1 gap-1.5">
                    <li>
                      <a
                        href="mailto:nurdinebacar@gmail.com"
                        className="inline-flex items-center gap-2 text-sm text-neutral-100 hover:underline"
                        title="Enviar email"
                        aria-label="Enviar email para nurdinebacar@gmail.com"
                      >
                        <Mail className="w-4 h-4" /> nurdinebacar@gmail.com
                      </a>
                    </li>

                    <li>
                      <a
                        href="tel:+258845636664"
                        className="inline-flex items-center gap-2 text-sm text-neutral-100 hover:underline"
                        title="Ligar para (+258) 84563 6664"
                        aria-label="Ligar para (+258) 84563 6664"
                      >
                        <Phone className="w-4 h-4" /> (+258) 84563 6664
                      </a>
                    </li>

                    <li>
                      <a
                        href="tel:+25884563666"
                        className="inline-flex items-center gap-2 text-sm text-neutral-100 hover:underline"
                        title="Ligar para (+258) 84563 666"
                        aria-label="Ligar para (+258) 84563 666"
                      >
                        <Phone className="w-4 h-4" /> (+258) 84563 666
                      </a>
                    </li>
                  </ul>
                </article>
                <article className="">
                  <h3 className="font-semibold text-xl mb-2">Localização</h3>
                  <p>Cidade de Maputo, Moçambique</p>
                </article>
              </div>
            </section>

            <hr className="w-full rounded-2xl bg-white my-8" />

            <section
              id="links"
              className="flex flex-col md:flex-row items-center justify-center gap-3 md:gap-8"
            >
              <Link className="flex gap-2 items-center" href="/">
                Incio Produtos <MoveUpRight size={18} />
              </Link>
              <Link className="flex gap-2 items-center" href="/">
                Produtos <MoveUpRight size={18} />{" "}
              </Link>
              <Link className="flex gap-2 items-center" href="/">
                Serviços Produtos <MoveUpRight size={18} />
              </Link>
              <Link className="flex gap-2 items-center" href="/">
                Sobre Nós Produtos <MoveUpRight size={18} />
              </Link>
            </section>
          </article>
        </footer>
      </body>
    </html>
  );
}
